"""Initial models

Revision ID: a5f89d2d3f01
Revises: 
Create Date: 2025-11-19 07:47:33.722650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5f89d2d3f01'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('password_hash', sa.String(length=255), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table(
        'companies',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('website', sa.String(length=255), nullable=True),
        sa.Column('location', sa.String(length=255), nullable=True),
        sa.Column('industry', sa.String(length=100), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_companies_user_id', 'users', ['user_id'], ['id'])

    op.create_table(
        'onboarding_data',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('target_role', sa.String(length=255), nullable=False),
        sa.Column('target_industry', sa.String(length=255), nullable=True),
        sa.Column('experience_level', sa.String(length=50), nullable=True),
        sa.Column('dream_milestone', sa.Text(), nullable=True),
        sa.Column('skills', sa.Text(), nullable=True),
        sa.Column('preferred_locations', sa.Text(), nullable=True),
        sa.Column('availability', sa.String(length=50), nullable=True),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('onboarding_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_onboarding_data_user_id'), ['user_id'], unique=True)
        batch_op.create_foreign_key('fk_onboarding_data_user_id', 'users', ['user_id'], ['id'])

    op.create_table(
        'goals',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('week_start', sa.Date(), nullable=False),
        sa.Column('applications_goal', sa.Integer(), nullable=True, server_default=sa.text('0')),
        sa.Column('applications_current', sa.Integer(), nullable=True, server_default=sa.text('0')),
        sa.Column('outreach_goal', sa.Integer(), nullable=True, server_default=sa.text('0')),
        sa.Column('outreach_current', sa.Integer(), nullable=True, server_default=sa.text('0')),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'week_start', name='unique_user_week_goal')
    )
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goals_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_goals_week_start'), ['week_start'], unique=False)
        batch_op.create_foreign_key('fk_goals_user_id', 'users', ['user_id'], ['id'])

    op.create_table(
        'streaks',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('current_streak', sa.Integer(), nullable=True, server_default=sa.text('0')),
        sa.Column('longest_streak', sa.Integer(), nullable=True, server_default=sa.text('0')),
        sa.Column('last_activity_date', sa.Date(), nullable=True),
        sa.Column('total_points', sa.Integer(), nullable=True, server_default=sa.text('0')),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('streaks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_streaks_user_id'), ['user_id'], unique=True)
        batch_op.create_foreign_key('fk_streaks_user_id', 'users', ['user_id'], ['id'])

    op.create_table(
        'applications',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('company_id', sa.Integer(), nullable=False),
        sa.Column('job_title', sa.String(length=255), nullable=False),
        sa.Column('job_url', sa.String(length=255), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=False, server_default='Planned'),
        sa.Column('applied_date', sa.Date(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applications_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_status'), ['status'], unique=False)
        batch_op.create_foreign_key('fk_applications_user_id', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('fk_applications_company_id', 'companies', ['company_id'], ['id'])

    op.create_table(
        'contacts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('company_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=True),
        sa.Column('linkedin_url', sa.String(length=255), nullable=True),
        sa.Column('role', sa.String(length=255), nullable=True),
        sa.Column('source', sa.String(length=50), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('company_id', 'email', name='unique_company_email')
    )
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contacts_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_contacts_company_id', 'companies', ['company_id'], ['id'])
        batch_op.create_foreign_key('fk_contacts_user_id', 'users', ['user_id'], ['id'])

    op.create_table(
        'outreach_activities',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('application_id', sa.Integer(), nullable=True),
        sa.Column('company_id', sa.Integer(), nullable=True),
        sa.Column('contact_id', sa.Integer(), nullable=False),
        sa.Column('channel', sa.String(length=50), nullable=False),
        sa.Column('message_template', sa.Text(), nullable=True),
        sa.Column('sent_date', sa.DateTime(), nullable=False),
        sa.Column('follow_up_date', sa.DateTime(), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=True, server_default=sa.text("'Sent'")),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outreach_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outreach_activities_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outreach_activities_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outreach_activities_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outreach_activities_contact_id'), ['contact_id'], unique=False)
        batch_op.create_foreign_key('fk_outreach_activities_user_id', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('fk_outreach_activities_application_id', 'applications', ['application_id'], ['id'])
        batch_op.create_foreign_key('fk_outreach_activities_company_id', 'companies', ['company_id'], ['id'])
        batch_op.create_foreign_key('fk_outreach_activities_contact_id', 'contacts', ['contact_id'], ['id'])
        batch_op.create_check_constraint(
            'check_outreach_link',
            '(application_id IS NOT NULL AND company_id IS NULL) OR (application_id IS NULL AND company_id IS NOT NULL)'
        )

    op.create_table(
        'cv_analyses',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('application_id', sa.Integer(), nullable=True),
        sa.Column('cv_filename', sa.String(length=255), nullable=True),
        sa.Column('job_description', sa.Text(), nullable=False),
        sa.Column('ats_score', sa.Integer(), nullable=True),
        sa.Column('matched_keywords', sa.Text(), nullable=True),
        sa.Column('missing_keywords', sa.Text(), nullable=True),
        sa.Column('suggestions', sa.Text(), nullable=True),
        sa.Column('api_used', sa.String(length=50), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cv_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cv_analyses_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cv_analyses_application_id'), ['application_id'], unique=False)
        batch_op.create_foreign_key('fk_cv_analyses_user_id', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('fk_cv_analyses_application_id', 'applications', ['application_id'], ['id'])

    op.create_table(
        'notifications',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('type', sa.String(length=50), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('message', sa.Text(), nullable=True),
        sa.Column('related_type', sa.String(length=50), nullable=True),
        sa.Column('related_id', sa.Integer(), nullable=True),
        sa.Column('is_read', sa.Boolean(), nullable=True, server_default='false'),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_foreign_key('fk_notifications_user_id', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint('fk_notifications_user_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))
        batch_op.drop_index(batch_op.f('ix_notifications_type'))
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
    op.drop_table('notifications')

    with op.batch_alter_table('cv_analyses', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cv_analyses_user_id', type_='foreignkey')
        batch_op.drop_constraint('fk_cv_analyses_application_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_cv_analyses_user_id'))
        batch_op.drop_index(batch_op.f('ix_cv_analyses_application_id'))
    op.drop_table('cv_analyses')

    with op.batch_alter_table('outreach_activities', schema=None) as batch_op:
        batch_op.drop_constraint('check_outreach_link', type_='check')
        batch_op.drop_constraint('fk_outreach_activities_user_id', type_='foreignkey')
        batch_op.drop_constraint('fk_outreach_activities_application_id', type_='foreignkey')
        batch_op.drop_constraint('fk_outreach_activities_company_id', type_='foreignkey')
        batch_op.drop_constraint('fk_outreach_activities_contact_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_outreach_activities_user_id'))
        batch_op.drop_index(batch_op.f('ix_outreach_activities_application_id'))
        batch_op.drop_index(batch_op.f('ix_outreach_activities_company_id'))
        batch_op.drop_index(batch_op.f('ix_outreach_activities_contact_id'))
    op.drop_table('outreach_activities')

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_contacts_company_id', type_='foreignkey')
        batch_op.drop_constraint('fk_contacts_user_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_contacts_company_id'))
        batch_op.drop_index(batch_op.f('ix_contacts_user_id'))
    op.drop_table('contacts')

    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_constraint('fk_applications_user_id', type_='foreignkey')
        batch_op.drop_constraint('fk_applications_company_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_applications_status'))
        batch_op.drop_index(batch_op.f('ix_applications_company_id'))
        batch_op.drop_index(batch_op.f('ix_applications_user_id'))
    op.drop_table('applications')

    with op.batch_alter_table('streaks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_streaks_user_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_streaks_user_id'))
    op.drop_table('streaks')

    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_constraint('fk_goals_user_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_goals_week_start'))
        batch_op.drop_index(batch_op.f('ix_goals_user_id'))
    op.drop_table('goals')

    with op.batch_alter_table('onboarding_data', schema=None) as batch_op:
        batch_op.drop_constraint('fk_onboarding_data_user_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_onboarding_data_user_id'))
    op.drop_table('onboarding_data')

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_constraint('fk_companies_user_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_companies_user_id'))
    op.drop_table('companies')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
    op.drop_table('users')
    # ### end Alembic commands ###